const screens={menu:document.getElementById("mainMenu"),levels:document.getElementById("levelScreen"),game:document.getElementById("gameScreen"),how:document.getElementById("howScreen")};
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),cardsEl=document.getElementById("cards"),levelGridEl=document.getElementById("levelGrid"),levelTitleEl=document.getElementById("levelTitle"),levelDescEl=document.getElementById("levelDesc"),glowText=document.getElementById("glowText"),waveText=document.getElementById("waveText"),statusText=document.getElementById("statusText"),messageEl=document.getElementById("message");
const ROWS=5,COLS=9,CELL_W=86,CELL_H=82,GRID_X=80,GRID_Y=78;
const images={},imageList={campfr:"assets/plant-campfr.png",treeGun:"assets/plant-tree-gun.png",kaboom:"assets/plant-el-kaboom.png",basicDerp:"assets/enemy-basic-derp.png",armoredDerp:"assets/enemy-armored-derp.png",fastDerp:"assets/enemy-fast-derp.png",glow:"assets/resource-glow.png",grass:"assets/tile-grass.png"};
for(const[k,src]of Object.entries(imageList)){images[k]=new Image();images[k].src=src}
const LEVELS=[
{name:"1-1",title:"First Derp",desc:"A regular lawn with regular bad decisions.",startGlow:75,waves:[[{type:"basic",row:2,delay:120}],[{type:"basic",row:1,delay:100},{type:"basic",row:3,delay:220}]],lava:[]},
{name:"1-2",title:"Two Derps Maybe",desc:"More derps walk at you. Horrifying.",startGlow:75,waves:[[{type:"basic",row:0,delay:80},{type:"basic",row:4,delay:260}],[{type:"basic",row:2,delay:80},{type:"fast",row:3,delay:250}]],lava:[]},
{name:"1-3",title:"Fast Boi Test",desc:"Fast Da Boiiiiii joins the argument.",startGlow:100,waves:[[{type:"fast",row:1,delay:120}],[{type:"basic",row:2,delay:90},{type:"fast",row:2,delay:250},{type:"basic",row:4,delay:420}]],lava:[]},
{name:"1-4",title:"Armor Moment",desc:"Armored Da Boiiiiii is mildly rude.",startGlow:100,waves:[[{type:"armored",row:2,delay:180}],[{type:"basic",row:1,delay:90},{type:"armored",row:3,delay:300}]],lava:[]},
{name:"1-5",title:"Mor Level Preview",desc:"Lava tiles exist. Do not plant there.",startGlow:125,waves:[[{type:"basic",row:0,delay:100},{type:"basic",row:4,delay:240}],[{type:"fast",row:2,delay:130},{type:"armored",row:3,delay:360}]],lava:[[4,1],[4,2],[4,3]]},
{name:"1-6",title:"Kaboom Lessons",desc:"El Kaboom solves problems loudly.",startGlow:150,waves:[[{type:"basic",row:1,delay:80},{type:"basic",row:1,delay:180},{type:"basic",row:1,delay:280}],[{type:"armored",row:2,delay:170}]],lava:[]},
{name:"1-7",title:"Lawn Malfunction",desc:"This lawn is not inspected.",startGlow:150,waves:[[{type:"fast",row:0,delay:120},{type:"fast",row:4,delay:250}],[{type:"basic",row:2,delay:100},{type:"armored",row:2,delay:320}]],lava:[[2,0],[6,4]]},
{name:"1-8",title:"Derp Stack",desc:"Many derps. Concerning quantity.",startGlow:175,waves:[[{type:"basic",row:0,delay:80},{type:"basic",row:1,delay:130},{type:"basic",row:2,delay:180}],[{type:"basic",row:3,delay:80},{type:"fast",row:4,delay:240},{type:"armored",row:1,delay:400}]],lava:[]},
{name:"1-9",title:"Actual Problem",desc:"The derps found shoes.",startGlow:200,waves:[[{type:"fast",row:0,delay:80},{type:"fast",row:2,delay:190},{type:"fast",row:4,delay:300}],[{type:"armored",row:1,delay:120},{type:"armored",row:3,delay:360}]],lava:[[3,2],[5,2]]},
{name:"1-10",title:"The Derpening",desc:"Final level of world 1. Very serious.",startGlow:225,waves:[[{type:"basic",row:0,delay:70},{type:"basic",row:2,delay:160},{type:"basic",row:4,delay:250}],[{type:"fast",row:1,delay:80},{type:"armored",row:2,delay:280},{type:"fast",row:3,delay:460}],[{type:"armored",row:0,delay:110},{type:"armored",row:4,delay:270},{type:"fast",row:2,delay:430}]],lava:[[4,0],[4,1],[4,3],[4,4]]}];
const PLANTS={campfr:{name:"Campfr",cost:50,hp:80,img:"campfr",desc:"Makes Glow."},treeGun:{name:"Tree Gun",cost:100,hp:100,img:"treeGun",desc:"Shoots derps."},kaboom:{name:"El Kaboom",cost:150,hp:40,img:"kaboom",desc:"Explodes."}};
const ENEMIES={basic:{name:"Da Boiiiiii",hp:90,speed:.28,damage:10,img:"basicDerp"},armored:{name:"Armored Da Boiiiiii",hp:190,speed:.22,damage:16,img:"armoredDerp"},fast:{name:"Fast Da Boiiiiii",hp:65,speed:.48,damage:8,img:"fastDerp"}};
let state=null;function showScreen(n){for(const s of Object.values(screens))s.classList.remove("active");screens[n].classList.add("active")}
function initLevelButtons(){levelGridEl.innerHTML="";LEVELS.forEach((level,i)=>{const btn=document.createElement("button");btn.className="level-tile";btn.textContent=level.name+" - "+level.title;btn.onclick=()=>startLevel(i);levelGridEl.appendChild(btn)})}
function initCards(){cardsEl.innerHTML="";for(const[id,plant]of Object.entries(PLANTS)){const card=document.createElement("button");card.className="card";card.dataset.plant=id;card.innerHTML=`<img src="${imageList[plant.img]}" alt="${plant.name}"><b>${plant.name}</b><span>${plant.cost} Glow</span><br><span>${plant.desc}</span>`;card.onclick=()=>selectPlant(id);cardsEl.appendChild(card)}}
function selectPlant(id){state.selectedPlant=id;document.querySelectorAll(".card").forEach(c=>c.classList.toggle("selected",c.dataset.plant===id));say(`Selected ${PLANTS[id].name}.`)}
function startLevel(index){const level=LEVELS[index];state={levelIndex:index,level,glow:level.startGlow,waveIndex:0,waveTimer:0,waveSpawnIndex:0,betweenWaveTimer:180,grid:[],plants:[],enemies:[],projectiles:[],explosions:[],particles:[],selectedPlant:"campfr",running:true,won:false,lost:false,tick:0,message:"Protect the lawn from questionable creatures.",messageTimer:240};for(let r=0;r<ROWS;r++){state.grid[r]=[];for(let c=0;c<COLS;c++)state.grid[r][c]={tile:"grass",plant:null}}for(const[c,r]of level.lava||[])if(state.grid[r]&&state.grid[r][c])state.grid[r][c].tile="lava";levelTitleEl.textContent=level.name+": "+level.title;levelDescEl.textContent=level.desc;showScreen("game");initCards();selectPlant("campfr");updateHud();requestAnimationFrame(gameLoop)}
function say(text,time=180){if(!state)return;state.message=text;state.messageTimer=time;messageEl.textContent=text}function updateHud(){if(!state)return;glowText.textContent=`Glow: ${state.glow}`;waveText.textContent=`Wave: ${Math.min(state.waveIndex+1,state.level.waves.length)}/${state.level.waves.length}`;statusText.textContent=state.lost?"Lost":state.won?"Won":"Derping"}
function gridFromMouse(evt){const rect=canvas.getBoundingClientRect(),mx=(evt.clientX-rect.left)*(canvas.width/rect.width),my=(evt.clientY-rect.top)*(canvas.height/rect.height),c=Math.floor((mx-GRID_X)/CELL_W),r=Math.floor((my-GRID_Y)/CELL_H);if(r<0||r>=ROWS||c<0||c>=COLS)return null;return{r,c,x:mx,y:my}}
function plantAt(r,c,type){const cell=state.grid[r][c],plantDef=PLANTS[type];if(cell.tile==="lava"){say("You cannot plant on lava. Mor Level says no.");return}if(cell.plant){say("There is already something there.");return}if(state.glow<plantDef.cost){say("Not enough Glow.");return}state.glow-=plantDef.cost;const plant={id:type,r,c,hp:plantDef.hp,maxHp:plantDef.hp,cooldown:type==="campfr"?900:type==="treeGun"?120:180,fuse:type==="kaboom"?90:0};cell.plant=plant;state.plants.push(plant);say(`${plantDef.name} placed.`);updateHud()}
function spawnEnemy(type,row){const def=ENEMIES[type];state.enemies.push({type,row,x:GRID_X+COLS*CELL_W+40,y:GRID_Y+row*CELL_H+CELL_H/2,hp:def.hp,maxHp:def.hp,speed:def.speed,damage:def.damage,biteCooldown:0})}
function gameLoop(){if(!state||!screens.game.classList.contains("active"))return;update();draw();if(!state.lost&&!state.won)requestAnimationFrame(gameLoop)}
function update(){state.tick++;if(state.messageTimer>0)state.messageTimer--;updateWaves();updatePlants();updateProjectiles();updateEnemies();updateExplosions();updateHud()}
function updateWaves(){if(state.waveIndex>=state.level.waves.length){if(state.enemies.length===0&&!state.won){state.won=true;say("You won. The derps are confused forever.",999999)}return}if(state.betweenWaveTimer>0){state.betweenWaveTimer--;return}const wave=state.level.waves[state.waveIndex];state.waveTimer++;while(state.waveSpawnIndex<wave.length&&state.waveTimer>=wave[state.waveSpawnIndex].delay){const spawn=wave[state.waveSpawnIndex];spawnEnemy(spawn.type,spawn.row);state.waveSpawnIndex++}if(state.waveSpawnIndex>=wave.length&&state.enemies.length===0){state.waveIndex++;state.waveSpawnIndex=0;state.waveTimer=0;state.betweenWaveTimer=240;if(state.waveIndex<state.level.waves.length)say("Next wave soon.")}}
function updatePlants(){for(const plant of[...state.plants]){plant.cooldown--;if(plant.id==="campfr"&&plant.cooldown<=0){state.glow+=25;plant.cooldown=900;popParticle(GRID_X+plant.c*CELL_W+CELL_W/2,GRID_Y+plant.r*CELL_H+20,"#ffe95a")}if(plant.id==="treeGun"){const hasTarget=state.enemies.some(e=>e.row===plant.r&&e.x>GRID_X+plant.c*CELL_W);if(plant.cooldown<=0&&hasTarget){state.projectiles.push({x:GRID_X+plant.c*CELL_W+CELL_W*.65,y:GRID_Y+plant.r*CELL_H+CELL_H*.45,row:plant.r,speed:4.5,damage:24});plant.cooldown=115}}if(plant.id==="kaboom"){plant.fuse--;if(plant.fuse<=0)explodePlant(plant)}}}
function updateProjectiles(){for(let i=state.projectiles.length-1;i>=0;i--){const p=state.projectiles[i];p.x+=p.speed;const hit=state.enemies.find(e=>e.row===p.row&&Math.abs(e.x-p.x)<26);if(hit){hit.hp-=p.damage;state.projectiles.splice(i,1);popParticle(hit.x,hit.y,"#b8754a");continue}if(p.x>canvas.width+40)state.projectiles.splice(i,1)}}
function updateEnemies(){for(let i=state.enemies.length-1;i>=0;i--){const e=state.enemies[i];if(e.hp<=0){state.enemies.splice(i,1);state.glow+=5;popParticle(e.x,e.y,"#ffffff");continue}const col=Math.floor((e.x-GRID_X)/CELL_W),plant=state.grid[e.row]?.[col]?.plant;if(plant&&Math.abs(e.x-(GRID_X+col*CELL_W+CELL_W/2))<36){if(e.biteCooldown<=0){plant.hp-=e.damage;e.biteCooldown=60;popParticle(GRID_X+col*CELL_W+CELL_W/2,GRID_Y+e.row*CELL_H+CELL_H/2,"#ff4444");if(plant.hp<=0){state.grid[plant.r][plant.c].plant=null;state.plants=state.plants.filter(p=>p!==plant)}}else e.biteCooldown--;continue}e.x-=e.speed;if(e.x<GRID_X-50){state.lost=true;say("A derp entered your house. It is over.",999999);return}}}
function explodePlant(plant){const cx=GRID_X+plant.c*CELL_W+CELL_W/2,cy=GRID_Y+plant.r*CELL_H+CELL_H/2;for(const e of state.enemies){if(Math.hypot(e.x-cx,e.y-cy)<140)e.hp-=180}state.explosions.push({x:cx,y:cy,radius:10,life:24});state.grid[plant.r][plant.c].plant=null;state.plants=state.plants.filter(p=>p!==plant);say("EL KABOOM.")}
function updateExplosions(){for(let i=state.explosions.length-1;i>=0;i--){const ex=state.explosions[i];ex.radius+=7;ex.life--;if(ex.life<=0)state.explosions.splice(i,1)}for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.y-=.4;p.life--;if(p.life<=0)state.particles.splice(i,1)}}function popParticle(x,y,color){state.particles.push({x,y,color,life:45})}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);drawBoard();drawPlants();drawEnemies();drawProjectiles();drawExplosions();drawParticles()}
function drawBoard(){ctx.fillStyle="#5fb846";ctx.fillRect(0,0,canvas.width,canvas.height);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const x=GRID_X+c*CELL_W,y=GRID_Y+r*CELL_H,cell=state.grid[r][c];if(cell.tile==="lava"){ctx.fillStyle="#e85b17";ctx.fillRect(x,y,CELL_W,CELL_H);ctx.fillStyle="#ffdd44";ctx.fillRect(x+8,y+28,CELL_W-16,8)}else if(images.grass.complete)ctx.drawImage(images.grass,x+4,y+4,CELL_W-8,CELL_H-8);else{ctx.fillStyle=(r+c)%2?"#6fcc50":"#72d455";ctx.fillRect(x,y,CELL_W,CELL_H)}ctx.strokeStyle="#1c8c39";ctx.lineWidth=2;ctx.strokeRect(x,y,CELL_W,CELL_H)}}
function drawPlants(){for(const plant of state.plants){const def=PLANTS[plant.id],x=GRID_X+plant.c*CELL_W+6,y=GRID_Y+plant.r*CELL_H+3,img=images[def.img];if(img&&img.complete)ctx.drawImage(img,x,y,CELL_W-12,CELL_H-8);else{ctx.fillStyle="#159948";ctx.fillRect(x+10,y+10,CELL_W-30,CELL_H-25)}if(plant.hp<plant.maxHp){ctx.fillStyle="#000";ctx.fillRect(x+8,y+CELL_H-10,CELL_W-24,5);ctx.fillStyle="#46ff46";ctx.fillRect(x+8,y+CELL_H-10,(CELL_W-24)*(plant.hp/plant.maxHp),5)}}}
function drawEnemies(){for(const e of state.enemies){const def=ENEMIES[e.type],img=images[def.img];if(img&&img.complete)ctx.drawImage(img,e.x-38,e.y-42,76,76);else{ctx.fillStyle="#eee";ctx.fillRect(e.x-20,e.y-28,40,56)}ctx.fillStyle="#000";ctx.fillRect(e.x-24,e.y-48,48,5);ctx.fillStyle="#ff3333";ctx.fillRect(e.x-24,e.y-48,48*(e.hp/e.maxHp),5)}}
function drawProjectiles(){ctx.fillStyle="#5b2b16";for(const p of state.projectiles)ctx.fillRect(p.x,p.y,18,6)}function drawExplosions(){for(const ex of state.explosions){ctx.strokeStyle=`rgba(255,90,20,${ex.life/24})`;ctx.lineWidth=8;ctx.beginPath();ctx.arc(ex.x,ex.y,ex.radius,0,Math.PI*2);ctx.stroke()}}function drawParticles(){for(const p of state.particles){ctx.globalAlpha=p.life/45;ctx.fillStyle=p.color;ctx.fillRect(p.x-5,p.y-5,10,10);ctx.globalAlpha=1}}
canvas.addEventListener("click",evt=>{if(!state||!state.running||state.lost||state.won)return;const pos=gridFromMouse(evt);if(!pos)return;plantAt(pos.r,pos.c,state.selectedPlant)});document.getElementById("playBtn").onclick=()=>startLevel(0);document.getElementById("levelBtn").onclick=()=>showScreen("levels");document.getElementById("howBtn").onclick=()=>showScreen("how");document.getElementById("backFromLevels").onclick=()=>showScreen("menu");document.getElementById("backFromHow").onclick=()=>showScreen("menu");document.getElementById("backToMenu").onclick=()=>showScreen("menu");document.getElementById("restartLevel").onclick=()=>startLevel(state?.levelIndex||0);initLevelButtons();showScreen("menu");
