// PAD Modder v1 - creates level objects compatible with Plants Against Derps v2.
"use strict";
const STORAGE_KEY="pad_custom_levels_v1";
const BACKGROUNDS=["forest","desert","cloud","milkyway","chess"];
const MUSIC=["world1","battle","desert","victory","finalBoss"];
const ENEMIES = [
  "basic",
  "armored",
  "fast",
  "assasinRover",
  "mechaDerp",

  "alien",
  "alienGun",
  "droneSaw",
  "alienGod",
  "alienFinalBoss"
];
const MAX_WAVES=15,MAX_ENEMIES_PER_WAVE=12;
let current=makeDefaultLevel();
let savedLevels=loadSavedLevels();
function clamp(num,min,max){return Math.max(min,Math.min(max,Number(num)||0));}
function makeDefaultLevel(){return{name:"Custom-1",title:"My Weird Level",desc:"Made in PAD Modder.",startGlow:200,background:"forest",music:"battle",waves:[[{type:"basic",row:2,delay:120}]],lava:[]};}
function loadSavedLevels(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");}catch(err){console.warn("Could not load saved levels:",err);return[];}}
function saveSavedLevels(){localStorage.setItem(STORAGE_KEY,JSON.stringify(savedLevels));}
function encodeLevel(level){return btoa(unescape(encodeURIComponent(JSON.stringify(level))));}
function decodeLevel(code){return JSON.parse(decodeURIComponent(escape(atob(code.trim()))));}
function $(id){return document.getElementById(id);}
function fillDropdowns(){const bg=$("backgroundSelect"),music=$("musicSelect");bg.innerHTML="";music.innerHTML="";for(const item of BACKGROUNDS){const opt=document.createElement("option");opt.value=item;opt.textContent=item;bg.appendChild(opt);}for(const item of MUSIC){const opt=document.createElement("option");opt.value=item;opt.textContent=item;music.appendChild(opt);}}
function syncFormFromLevel(){sanitizeLevel(current);$("levelName").value=current.name;$("levelTitle").value=current.title;$("levelDesc").value=current.desc;$("startGlow").value=current.startGlow;$("backgroundSelect").value=current.background;$("musicSelect").value=current.music;renderLavaGrid();renderWaves();renderSavedLevels();updatePreview();}
function syncLevelFromForm(){current.name=($("levelName").value||"Custom-1").trim().slice(0,24);current.title=($("levelTitle").value||"Untitled Level").trim().slice(0,50);current.desc=($("levelDesc").value||"Made in PAD Modder.").trim().slice(0,120);current.startGlow=clamp($("startGlow").value,0,5000);current.background=$("backgroundSelect").value;current.music=$("musicSelect").value;sanitizeLevel(current);updatePreview();}
function sanitizeLevel(level){level.name=String(level.name||"Custom-1").slice(0,24);level.title=String(level.title||"Untitled Level").slice(0,50);level.desc=String(level.desc||"Made in PAD Modder.").slice(0,120);level.startGlow=clamp(level.startGlow,0,5000);if(!BACKGROUNDS.includes(level.background))level.background="forest";if(!MUSIC.includes(level.music))level.music="battle";level.lava=Array.isArray(level.lava)?level.lava:[];level.lava=level.lava.filter(pair=>Array.isArray(pair)&&pair.length>=2).map(pair=>[clamp(pair[0],0,8),clamp(pair[1],0,4)]).filter((pair,index,arr)=>arr.findIndex(other=>other[0]===pair[0]&&other[1]===pair[1])===index);level.waves=Array.isArray(level.waves)?level.waves.slice(0,MAX_WAVES):[[]];if(level.waves.length===0)level.waves.push([]);level.waves=level.waves.map(wave=>{if(!Array.isArray(wave))return[];return wave.slice(0,MAX_ENEMIES_PER_WAVE).map(enemy=>({type:ENEMIES.includes(enemy.type)?enemy.type:"basic",row:clamp(enemy.row,0,4),delay:clamp(enemy.delay,30,1200)}));});return level;}
function renderLavaGrid(){const grid=$("lavaGrid");grid.innerHTML="";const lavaSet=new Set(current.lava.map(([col,row])=>`${col},${row}`));for(let row=0;row<5;row++){for(let col=0;col<9;col++){const key=`${col},${row}`,btn=document.createElement("button");btn.className=`lava-cell ${lavaSet.has(key)?"on":""}`;btn.textContent=`${col},${row}`;btn.title=lavaSet.has(key)?"Lava tile":"Normal tile";btn.addEventListener("click",()=>toggleLava(col,row));grid.appendChild(btn);}}}
function toggleLava(col,row){const index=current.lava.findIndex(pair=>pair[0]===col&&pair[1]===row);if(index>=0)current.lava.splice(index,1);else current.lava.push([col,row]);syncLevelFromForm();renderLavaGrid();}
function renderWaves(){const area=$("wavesArea");area.innerHTML="";current.waves.forEach((wave,waveIndex)=>{const card=document.createElement("section");card.className="wave-card";const head=document.createElement("div");head.className="wave-head";head.innerHTML=`<h3>Wave ${waveIndex+1}</h3><div><button class="btn ghost" data-add="${waveIndex}">Add Enemy</button> <button class="btn ghost danger" data-remove-wave="${waveIndex}">Remove Wave</button></div>`;card.appendChild(head);if(wave.length===0){const empty=document.createElement("p");empty.className="hint";empty.textContent="No enemies yet. Add one.";card.appendChild(empty);}wave.forEach((enemy,enemyIndex)=>{const row=document.createElement("div");row.className="enemy-row";row.innerHTML=`<label>Enemy<select data-wave="${waveIndex}" data-enemy="${enemyIndex}" data-field="type">${ENEMIES.map(type=>`<option value="${type}" ${enemy.type===type?"selected":""}>${type}</option>`).join("")}</select></label><label>Row<input type="number" min="0" max="4" value="${enemy.row}" data-wave="${waveIndex}" data-enemy="${enemyIndex}" data-field="row" /></label><label>Delay<input type="number" min="30" max="1200" value="${enemy.delay}" data-wave="${waveIndex}" data-enemy="${enemyIndex}" data-field="delay" /></label><button title="Remove enemy" data-remove-enemy="${waveIndex},${enemyIndex}">X</button>`;card.appendChild(row);});area.appendChild(card);});area.querySelectorAll("[data-add]").forEach(btn=>btn.addEventListener("click",()=>addEnemy(Number(btn.dataset.add))));area.querySelectorAll("[data-remove-wave]").forEach(btn=>btn.addEventListener("click",()=>removeWave(Number(btn.dataset.removeWave))));area.querySelectorAll("[data-remove-enemy]").forEach(btn=>btn.addEventListener("click",()=>{const[waveIndex,enemyIndex]=btn.dataset.removeEnemy.split(",").map(Number);current.waves[waveIndex].splice(enemyIndex,1);syncLevelFromForm();renderWaves();}));area.querySelectorAll("input, select").forEach(input=>input.addEventListener("input",()=>{const waveIndex=Number(input.dataset.wave),enemyIndex=Number(input.dataset.enemy),field=input.dataset.field;if(!current.waves[waveIndex]||!current.waves[waveIndex][enemyIndex])return;if(field==="type")current.waves[waveIndex][enemyIndex].type=input.value;if(field==="row")current.waves[waveIndex][enemyIndex].row=clamp(input.value,0,4);if(field==="delay")current.waves[waveIndex][enemyIndex].delay=clamp(input.value,30,1200);syncLevelFromForm();}));}
function addWave(){if(current.waves.length>=MAX_WAVES){alert("Max 5 waves for now.");return;}current.waves.push([]);syncLevelFromForm();renderWaves();}
function removeWave(index){if(current.waves.length<=1){alert("A level needs at least 1 wave.");return;}current.waves.splice(index,1);syncLevelFromForm();renderWaves();}
function addEnemy(waveIndex){const wave=current.waves[waveIndex];if(!wave)return;if(wave.length>=MAX_ENEMIES_PER_WAVE){alert("Max 12 enemies per wave for now.");return;}wave.push({type:"basic",row:2,delay:120+wave.length*120});syncLevelFromForm();renderWaves();}
function renderSavedLevels(){const list=$("savedLevels");list.innerHTML="";if(savedLevels.length===0){list.innerHTML=`<p class="hint">No saved levels yet.</p>`;return;}savedLevels.forEach((level,index)=>{const item=document.createElement("div");item.className="saved-item";item.innerHTML=`<b>${level.name||`Custom-${index+1}`}</b><div>${level.title||"Untitled Level"}</div><div class="saved-actions"><button data-load="${index}">Load</button><button data-copy="${index}">Copy Code</button><button data-delete="${index}">Delete</button></div>`;list.appendChild(item);});list.querySelectorAll("[data-load]").forEach(btn=>btn.addEventListener("click",()=>{current=JSON.parse(JSON.stringify(savedLevels[Number(btn.dataset.load)]));syncFormFromLevel();}));list.querySelectorAll("[data-copy]").forEach(btn=>btn.addEventListener("click",()=>{const index=Number(btn.dataset.copy);$("shareBox").value=encodeLevel(savedLevels[index]);$("shareBox").select();navigator.clipboard?.writeText($("shareBox").value).catch(()=>{});}));list.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",()=>{const index=Number(btn.dataset.delete);if(!confirm("Delete this saved level?"))return;savedLevels.splice(index,1);saveSavedLevels();renderSavedLevels();}));}
function saveCurrentLevel(){syncLevelFromForm();const copy=JSON.parse(JSON.stringify(current));sanitizeLevel(copy);const existingIndex=savedLevels.findIndex(level=>level.name===copy.name);if(existingIndex>=0){if(!confirm("Replace saved level with the same name?"))return;savedLevels[existingIndex]=copy;}else savedLevels.push(copy);saveSavedLevels();renderSavedLevels();alert("Level saved to browser.");}
function updatePreview(){const preview=$("jsonPreview");if(preview)preview.textContent=JSON.stringify(sanitizeLevel(JSON.parse(JSON.stringify(current))),null,2);}
function exportCurrent(){syncLevelFromForm();$("shareBox").value=encodeLevel(current);$("shareBox").select();navigator.clipboard?.writeText($("shareBox").value).catch(()=>{});}
function importFromBox(){try{const imported=decodeLevel($("shareBox").value);current=sanitizeLevel(imported);syncFormFromLevel();alert("Imported level.");}catch(err){alert("Import failed. The code might be broken.");console.warn(err);}}
function hookEvents(){["levelName","levelTitle","levelDesc","startGlow","backgroundSelect","musicSelect"].forEach(id=>$(id).addEventListener("input",syncLevelFromForm));$("newLevelBtn").onclick=()=>{if(!confirm("Start a new level? Unsaved changes will be lost."))return;current=makeDefaultLevel();syncFormFromLevel();};$("saveBtn").onclick=saveCurrentLevel;$("exportBtn").onclick=exportCurrent;$("importBtn").onclick=importFromBox;$("addWaveBtn").onclick=addWave;$("clearWavesBtn").onclick=()=>{if(!confirm("Clear all waves?"))return;current.waves=[[]];syncLevelFromForm();renderWaves();};$("clearLavaBtn").onclick=()=>{current.lava=[];syncLevelFromForm();renderLavaGrid();};}
function boot(){fillDropdowns();hookEvents();syncFormFromLevel();console.log("PAD Modder v1 loaded.");}
boot();
